# Generated by Django 5.1.7 on 2025-06-08 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_reviewanalysis'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reviewanalysis',
            name='tracker_rev_url_72fef1_idx',
        ),
        migrations.RemoveField(
            model_name='reviewanalysis',
            name='id',
        ),
        migrations.AlterField(
            model_name='reviewanalysis',
            name='url',
            field=models.ForeignKey(db_column='url', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tracker.scrapedproduct', to_field='url'),
        ),
    ]
